version: '3.9'

services:
  nextjs-app:
    build: .
    container_name: iot-dashboard-ex
    restart: always
    ports:
      - "8080:3002"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    networks:
      - webnet

networks:
  webnet:
    driver: bridge